name: Notificación de CI

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificación a ntfy.sh
        run: |
          MENSAJE="Se ha hecho push al repositorio main por Ashley Cabrera Mena. Repositorio: Ashcm18/hola-mundo-ci"
          curl -d "$MENSAJE" https://ntfy.sh/devops-itla
