name: Notificación CI/CD Profesional

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: |
          node hola.js || echo "Hola.js falló, pero seguimos con la notificación"

      - name: Enviar notificación a ntfy.sh
        if: always()
        env:
          ESTUDIANTE: "Ashley Cabrera Mena"
          REPO: "Ashcm18/hola-mundo-ci"
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          JOB_STATUS: ${{ job.status }}
        run: |
          # Determinar estado del build
          if [ "$JOB_STATUS" == "success" ]; then
            STATUS="Código subido exitosamente"
          else
            STATUS="Falló el build"
          fi

          # Construir mensaje completo
          MENSAJE="$STATUS a main por $ESTUDIANTE
Repositorio: $REPO
Commit: $COMMIT_MESSAGE
Hora: $(date)"

          # Enviar notificación a ntfy.sh
          curl -s -d "$MENSAJE" https://ntfy.sh/devops-itla
