name: CI/CD - Notificación funcional

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ejecutar hola.js
        run: node hola.js || echo "hola.js falló, continuamos con la notificación"

      - name: Enviar notificación a ntfy.sh
        if: always()
        env:
          ESTUDIANTE: "Ashley Cabrera Mena"
          REPO: "Ashcm18/hola-mundo-ci"
          BRANCH: ${{ github.ref_name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_SHA: ${{ github.event.head_commit.id }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          JOB_STATUS: ${{ job.status }}
        run: |
          # Determinar estado del build
          if [ "$JOB_STATUS" == "success" ]; then
            STATUS="BUILD EXITOSO"
          else
            STATUS="BUILD FALLIDO"
          fi

          # Crear mensaje completo dentro de una variable
          MENSAJE="$STATUS - DevOps ITLA
Build completado con estado: $STATUS
Repositorio: $REPO
Rama: $BRANCH
Autor: $ESTUDIANTE
Commit: $COMMIT_MESSAGE
SHA: $COMMIT_SHA
Logs: $WORKFLOW_URL"

          # Enviar notificación
          curl -s -d "$MENSAJE" https://ntfy.sh/devops-itla
