name: Notificación de CI

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificación a ntfy.sh
        env:
          COMMIT_AUTHOR: ${{ github.actor }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl -d "Push realizado al repositorio main
Autor: $COMMIT_AUTHOR
Mensaje: $COMMIT_MESSAGE" https://ntfy.sh/devops-itla
